version: '3'

services:
  revive:
    build: .
    ports:
      - 80:80
    links:
      - db
  db:
    image: mysql:8.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=revive
      - MYSQL_USER=revive
      - MYSQL_PASSWORD=revive
